package com.gem.evidencegraph.entity;

public enum DocumentType {
    GST_CERTIFICATE,
    UDYAM_CERTIFICATE,
    PAN_DOCUMENT,
    INCOME_TAX_DOCUMENT,
    EPFO_DOCUMENT,
    ESIC_DOCUMENT,
    OEM_AUTHORIZATION,
    MAKE_IN_INDIA_DOCUMENT,
    STARTUP_CERTIFICATE,
    NSIC_CERTIFICATE,
    DIGILOCKER_DOCUMENT,
    BLACKLIST_DECLARATION,
    OTHER
}
